// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lhclyjozptjpbprssxxm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxoY2x5am96cHRqcGJwcnNzeHhtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE1MDkwNDAsImV4cCI6MjA2NzA4NTA0MH0.HME4G52_h30-Hx_Qn915ALA6d43D4bNpZ32jcADlNL0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});